#!/bin/bash

RHEVM32_NEED_PKGS_ON_OS_DISK=/media/SWYum/Packages
INCLUDE_OS_RPMS_DIR=/root/rhevm_pkgs
ls $RHEVM32_NEED_PKGS_ON_OS_DISK > RHEVM32_NEED_PKGS_ON_OS_DISK
ls $INCLUDE_OS_RPMS_DIR > INCLUDE_OS_RPMS_LIST

RHEVM32_NEED_PKGS=`dirname $INCLUDE_OS_RPMS_DIR`/RHEVM32_NEED_PKGS
mkdir -p $RHEVM32_NEED_PKGS

for OS_PKGS in `cat INCLUDE_OS_RPMS_LIST` ; do
	for OS_PKGS_ON_DISK in `cat RHEVM32_NEED_PKGS_ON_OS_DISK` ;do
		if [ $OS_PKGS == $OS_PKGS_ON_DISK ];
			then /bin/cp -afv $INCLUDE_OS_RPMS_DIR/$OS_PKGS $RHEVM32_NEED_PKGS;
			break;
		fi
done
done
