#!/bin/bash

RHEVM32_ALL_RPMS_DIR=/media/RHEVM32
INCLUDE_OS_RPMS_DIR=/root/rhevm_pkgs
ls -R $RHEVM32_ALL_RPMS_DIR > RHEVM_32_ALL_RPMS_LIST
ls $INCLUDE_OS_RPMS_DIR > INCLUDE_OS_RPMS_LIST

RHEVM32_ALL_IN_RPM=`dirname $INCLUDE_OS_RPMS_DIR`/RHEVM32_ALL_IN_RPM
mkdir -p $RHEVM32_ALL_IN_RPM

for RHEVM_PKGS in `cat RHEVM_32_ALL_RPMS_LIST` ; do
	for OS_PKGS in `cat INCLUDE_OS_RPMS_LIST` ;do
		if [ $RHEVM_PKGS == $OS_PKGS ];
			then /bin/cp -afv $INCLUDE_OS_RPMS_DIR/$RHEVM_PKGS $RHEVM32_ALL_IN_RPM ;
			break;
		fi
done
done
